# Security Configuration

rate_limiting:
  enabled: true
  window_ms: 900000  # 15 minutes
  max_requests: 100
  whitelist:
    - "127.0.0.1"
    - "::1"

ip_whitelist:
  enabled: true
  allowed_ips:
    - "127.0.0.1"
    - "::1"
  allowed_ranges:
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"

cors:
  enabled: true
  allowed_origins:
    - "https://app.neardeepyield.com"
    - "https://dashboard.neardeepyield.com"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
  expose_headers:
    - "Content-Length"
  max_age: 86400
  credentials: true

security_headers:
  content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
  x_frame_options: "DENY"
  x_content_type_options: "nosniff"
  x_xss_protection: "1; mode=block"
  referrer_policy: "strict-origin-when-cross-origin"
  strict_transport_security: "max-age=31536000; includeSubDomains"

audit_logging:
  enabled: true
  log_path: "./logs/security"
  log_level: "info"
  events:
    - "authentication"
    - "authorization"
    - "contract_interaction"
    - "configuration_change"
    - "backup"
  retention_days: 90

backup:
  enabled: true
  frequency: "daily"
  retention_days: 30
  encryption: true
  locations:
    - type: "s3"
      bucket: "${BACKUP_BUCKET}"
      region: "us-east-1"

incident_response:
  alert_channels:
    - type: "slack"
      webhook: "${SLACK_WEBHOOK_URL}"
    - type: "email"
      address: "security@neardeepyield.com"
  severity_levels:
    - critical
    - high
    - medium
    - low
  response_team:
    - role: "security_lead"
      contact: "security-lead@neardeepyield.com"
    - role: "devops"
      contact: "devops@neardeepyield.com"

compliance:
  frameworks:
    - "SOC2"
    - "GDPR"
  data_retention:
    transaction_logs: 7
    audit_logs: 90
    backups: 30
  encryption:
    at_rest: true
    in_transit: true
    key_rotation: 90
