version: '3'
services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword123
      - DOCKER_INFLUXDB_INIT_ORG=near_yield
      - DOCKER_INFLUXDB_INIT_BUCKET=yield_metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your-super-secret-auth-token

volumes:
  influxdb_data:
